repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 22.1.0
- hooks:
  - args:
    - -rn
    - -sn
    - --errors-only
    - --extension-pkg-whitelist=wx
    - --disable=import-error
    entry: pylint
    id: pylint
    language: system
    name: pylint
    types:
    - python
  repo: local
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.4
