[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.3"
tag_format = "$version"
update_changelog_on_bump = true
version_files = [
    "src/__version__.py",
    "pyproject.toml:version",
]
